name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/kivy:latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Compiler l'APK avec Buildozer
        run: buildozer android debug

      - name: Publier l'APK compilé
        uses: actions/upload-artifact@v4
        with:
          name: djk-clean-apk
          path: bin/*.apk
